import React, { useRef, useImperativeHandle, forwardRef } from 'react';
import { View, Text, StyleSheet, Image, Dimensions, PixelRatio } from 'react-native';
import ViewShot from 'react-native-view-shot';
import { LinearGradient } from 'expo-linear-gradient';
import { AIFace } from '@/components/AIFace';
import { useTheme } from '@/providers/ThemeProvider';
import { Sparkles, Quote, ScanLine } from 'lucide-react-native';

const { width } = Dimensions.get('window');
const CARD_WIDTH = width * 0.85;

interface FirstSessionArtifactProps {
    userName?: string;
    insights: string[];
    date: string;
    title?: string;
}

export interface FirstSessionArtifactRef {
    capture: () => Promise<string>;
}

export const FirstSessionArtifact = forwardRef<FirstSessionArtifactRef, FirstSessionArtifactProps>(({
    userName,
    insights,
    date,
    title,
}, ref) => {
    const viewShotRef = useRef<ViewShot>(null);
    const { colors, isDark } = useTheme();

    const displayTitle = title
        ? (userName ? `${userName}'s ${title}` : title)
        : (userName ? `${userName}'s First Breakthrough` : 'My First Breakthrough');

    useImperativeHandle(ref, () => ({
        capture: async () => {
            if (viewShotRef.current?.capture) {
                return await viewShotRef.current.capture();
            }
            throw new Error('ViewShot ref not ready');
        },
    }));

    return (
        <ViewShot ref={viewShotRef} options={{ format: 'png', quality: 1.0, result: 'base64' }}>
            <LinearGradient
                colors={isDark ? ['#2D2A3E', '#1A1A2E'] : ['#FDFBF7', '#EBE7E2']}
                style={styles.card}
            >
                {/* Header / Branding */}
                <View style={styles.header}>
                    <Text style={[styles.brandText, { color: colors.textSecondary }]}>MAZŌ</Text>
                    <Text style={[styles.dateText, { color: colors.textTertiary }]}>{date}</Text>
                </View>

                {/* Central Visual */}
                <View style={styles.visualContainer}>
                    <View style={styles.glowContainer}>
                        <AIFace expression="happy" size={100} />
                    </View>
                </View>

                {/* User Celebration — Dynamic Title */}
                <Text style={[styles.title, { color: colors.text }]}>
                    {displayTitle}
                </Text>

                <View style={styles.divider} />

                {/* Insights List */}
                <View style={styles.insightsContainer}>
                    {insights.map((insight, index) => (
                        <View key={index} style={styles.insightRow}>
                            <Sparkles size={16} color={colors.accent} style={{ marginTop: 4 }} />
                            <Text style={[styles.insightText, { color: colors.text }]}>
                                {insight}
                            </Text>
                        </View>
                    ))}
                </View>

                {/* Footer / CTA */}
                <View style={styles.footer}>
                    <View style={styles.streakBadge}>
                        <Text style={styles.streakBadgeText}>Day 1 · Streak Started 🔥</Text>
                    </View>
                    <Text style={[styles.footerText, { color: colors.textTertiary }]}>
                        Generated by Mazō AI Coaching
                    </Text>
                    <Text style={[styles.linkText, { color: colors.accent }]}>mazo.app</Text>
                </View>

            </LinearGradient>
        </ViewShot>
    );
});

const styles = StyleSheet.create({
    card: {
        width: CARD_WIDTH,
        padding: 24,
        borderRadius: 24,
        alignItems: 'center',
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 5,
    },
    header: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    brandText: {
        fontFamily: 'PlusJakartaSans-Bold',
        fontSize: 14,
        letterSpacing: 2,
        fontWeight: '700',
    },
    dateText: {
        fontFamily: 'PlusJakartaSans-Medium',
        fontSize: 12,
    },
    visualContainer: {
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    glowContainer: {
        padding: 10,
    },
    title: {
        fontSize: 22,
        fontFamily: 'PlusJakartaSans-Bold',
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 16,
    },
    divider: {
        width: 40,
        height: 4,
        backgroundColor: '#E0E0E0',
        borderRadius: 2,
        marginBottom: 20,
    },
    insightsContainer: {
        width: '100%',
        gap: 12,
        marginBottom: 24,
    },
    insightRow: {
        flexDirection: 'row',
        gap: 12,
        paddingRight: 10,
    },
    insightText: {
        flex: 1,
        fontSize: 15,
        fontFamily: 'PlusJakartaSans-Medium',
        lineHeight: 22,
    },
    footer: {
        width: '100%',
        alignItems: 'center',
        gap: 4,
        marginTop: 8,
    },
    footerText: {
        fontSize: 12,
        fontFamily: 'PlusJakartaSans-Regular',
    },
    linkText: {
        fontSize: 12,
        fontFamily: 'PlusJakartaSans-Bold',
        fontWeight: '700',
    },
    streakBadge: {
        backgroundColor: 'rgba(255, 149, 0, 0.12)',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
        marginBottom: 10,
    },
    streakBadgeText: {
        fontSize: 13,
        fontFamily: 'PlusJakartaSans-Bold',
        fontWeight: '700',
        color: '#FF9500',
    },
});
